spring:
  application:
    name: client-app
---
server:
  port: 2003
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:client-app.jks
    key-store-password: 123456
    key-alias: client-app
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:client-app.jks
    trust-store-password: 123456
    trust-store-type: JKS
---
endpoint:
  server-app: https://localhost:2004/server-app/data